openapi: '3.0.2'
info:
  title: API Library
  version: '1.1.2'
  description: STD22085
servers:
  - url: https://libraryForBooks.com

tags:
  - name: Books
  - name: Author

paths:
  /books:
    get:
      tags:
        - "Books"
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: fromReleaseDate
          description: Filter books by release date starting from this date
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: toReleaseDate
          description: Filter books by release date ending before this date
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: page
          description: Page number for pagination, default 1
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          description: Number of items per page, default 50
          required: false
          schema:
            type: integer
            default: 50
       responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /authors:
  #TODO2: complete GET (can be filtered by name) - PUT - DELETE
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          #TODO1: set it as a component with properties : id, name, sex (M or F)
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
